# Dockerfile.jenkins
FROM jenkins/jenkins:lts

USER root

# Instalar Node.js y npm
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm

# Mantener Jenkins corriendo como root (ya lo tenés en docker-compose)
USER jenkins
